export const recents = [
  {
    id: 1,
    pontoId: 1,
    volId: 1,
    data: new Date().toLocaleDateString(),
    obs: "Observação da coleta 1",
    status: "Concluída",
  },
  {
    id: 2,
    pontoId: 2,
    volId: 2,
    data: new Date().toLocaleDateString(),
    obs: "Observação da coleta 2",
    status: "Concluída",
  },
  {
    id: 3,
    pontoId: 3,
    volId: 3,
    data: new Date().toLocaleDateString(),
    obs: "Observação da coleta 3",
    status: "Concluída",
  },
  {
    id: 4,
    pontoId: 4,
    volId: 4,
    data: new Date().toLocaleDateString(),
    obs: "Observação da coleta 4",
    status: "Concluída",
  },
];
export const pontos = [
  {
    id: 1,
    nome: "Escola Mun. Santos Dumont",
    endereco: "R. das Flores, 123",
    bairro: "Centro",
    status: "cheio",
    tampinhas: 48,
    contato: "Diretora Ana",
    tel: "(11) 98765-4321",
    mx: 42,
    my: 33,
    ultima: "15/09/2026",
  },
  {
    id: 2,
    nome: "Farmácia Popular Saúde",
    endereco: "Av. Brasil, 456",
    bairro: "Jd. América",
    status: "disponivel",
    tampinhas: 12,
    contato: "Marcos Souza",
    tel: "(11) 97654-3210",
    mx: 68,
    my: 58,
    ultima: "01/10/2026",
  },
  {
    id: 3,
    nome: "Supermercado Bom Preço",
    endereco: "R. XV de Novembro, 789",
    bairro: "Vila Nova",
    status: "cheio",
    tampinhas: 72,
    contato: "Gerente Pedro",
    tel: "(11) 96543-2109",
    mx: 22,
    my: 72,
    ultima: "20/09/2026",
  },
  {
    id: 4,
    nome: "Condomínio Jardins",
    endereco: "R. das Palmeiras, 101",
    bairro: "Jd. Europa",
    status: "aguardando",
    tampinhas: 31,
    contato: "Portaria",
    tel: "(11) 95432-1098",
    mx: 57,
    my: 22,
    ultima: "10/10/2026",
  },
  {
    id: 5,
    nome: "Academia Movimento",
    endereco: "Av. Paulista, 222",
    bairro: "Centro",
    status: "disponivel",
    tampinhas: 8,
    contato: "Renata Lima",
    tel: "(11) 94321-0987",
    mx: 78,
    my: 83,
    ultima: "05/10/2026",
  },
  {
    id: 6,
    nome: "EMEI Pequenos Gênios",
    endereco: "R. do Parque, 333",
    bairro: "Pq. Industrial",
    status: "cheio",
    tampinhas: 55,
    contato: "Coord. Beth",
    tel: "(11) 93210-9876",
    mx: 30,
    my: 51,
    ultima: "28/09/2026",
  },
];
export const voluntarios = [
  {
    id: 1,
    nome: "Carla Mendes",
    tel: "(11) 98888-1111",
    bairro: "Centro",
    total: 14,
    ativo: true,
    desde: "03/03/2026",
  },
  {
    id: 2,
    nome: "João Ribeiro",
    tel: "(11) 97777-2222",
    bairro: "Vila Nova",
    total: 9,
    ativo: true,
    desde: "15/04/2026",
  },
  {
    id: 3,
    nome: "Patrícia Nunes",
    tel: "(11) 96666-3333",
    bairro: "Jd. América",
    total: 21,
    ativo: true,
    desde: "10/01/2026",
  },
  {
    id: 4,
    nome: "Roberto Alves",
    tel: "(11) 95555-4444",
    bairro: "Jd. Europa",
    total: 5,
    ativo: false,
    desde: "22/06/2026",
  },
  {
    id: 5,
    nome: "Fernanda Costa",
    tel: "(11) 94444-5555",
    bairro: "Pq. Industrial",
    total: 17,
    ativo: true,
    desde: "08/02/2026",
  },
];
